### ISSUE TITLE
proxmox 8.2.2 / v0.9.8-4 / JovianDSS-Proxmox

### ISSUE THREAD

**Issue by mpimper** [open-e/JovianDSS-Proxmox#24]
i follow the Quick Start, 
inside storage cfg
joviandss: jdss-Pool-0
        pool_name Pool-0
        config /etc/pve/jdss-Pool-0.yaml
        content iso,backup,images,rootdir,vztmpl
        content_volume_name proxmox-content-jdss-pool-0
        content_volume_size 100
        path /mnt/jdss-Pool-0
        shared 1
        debug 0
        multipath 0
////////////////////////
inside /etc/pve/jdss-Pool-0.yaml
driver_use_ssl: False
target_prefix: 'iqn.2021-10.iscsi:'
jovian_block_size: '16K'
jovian_rest_send_repeats: 3
rest_api_addresses:
  - '192.168.19.98'
rest_api_port: 82
target_port: 3260
rest_api_login: 'admin'
rest_api_password: 'admin'
thin_provision: True
loglevel: info
logfile: /var/log/jdss-Pool-0.log
//////////////////
i run >>> pvesm list jdss-Pool-0 / and i have this error

pvesm list jdss-Pool-0
file /etc/pve/storage.cfg line 17 (section 'jdss-Pool-0') - unable to parse value of 'shared': unexpected property 'shared'
Error:
ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/bin/jdssc", line 172, in <module>
    main()
  File "/usr/local/bin/jdssc", line 167, in main
    cmd[args.pop('command')](args, uargs, jdss)
  File "/usr/lib/python3/dist-packages/jdssc/pool.py", line 53, in __init__
    self.pa[self.args.pop('pool_action')]()
  File "/usr/lib/python3/dist-packages/jdssc/pool.py", line 89, in volume
    volume.Volume(self.args, self.uargs, self.jdss)
  File "/usr/lib/python3/dist-packages/jdssc/volume.py", line 46, in __init__
    self.va[self.args.pop('volume_action')]()
  File "/usr/lib/python3/dist-packages/jdssc/volume.py", line 150, in get
    d = self.jdss.get_volume(volume,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jdssc/jovian_common/driver.py", line 1023, in get_volume
    data = self.ra.get_lun(name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jdssc/jovian_common/rest.py", line 269, in get_lun
    if not resp['error'] and resp['code'] == 200:
           ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Error:
ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/bin/jdssc", line 172, in <module>
    main()
  File "/usr/local/bin/jdssc", line 167, in main
    cmd[args.pop('command')](args, uargs, jdss)
  File "/usr/lib/python3/dist-packages/jdssc/pool.py", line 53, in __init__
    self.pa[self.args.pop('pool_action')]()
  File "/usr/lib/python3/dist-packages/jdssc/pool.py", line 92, in volumes
    volumes.Volumes(self.args, self.uargs, self.jdss)
  File "/usr/lib/python3/dist-packages/jdssc/volumes.py", line 46, in __init__
    self.vsa[action]()
  File "/usr/lib/python3/dist-packages/jdssc/volumes.py", line 113, in create
    self.jdss.create_volume(name, size,
  File "/usr/lib/python3/dist-packages/jdssc/jovian_common/driver.py", line 103, in create_volume
    self.ra.create_lun(vname,
  File "/usr/lib/python3/dist-packages/jdssc/jovian_common/rest.py", line 168, in create_lun
    if not resp["error"] and resp["code"] in (200, 201):
           ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
command '/usr/local/bin/jdssc -c /etc/pve/jdss-Pool-0.yaml pool Pool-0 volumes create -d -s 100G -n proxmox-content-jdss-pool-0' failed: exit code 1

 ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/bin/jdssc", line 172, in <module>
    main()
  File "/usr/local/bin/jdssc", line 167, in main
    cmd[args.pop('command')](args, uargs, jdss)
  File "/usr/lib/python3/dist-packages/jdssc/pool.py", line 53, in __init__
    self.pa[self.args.pop('pool_action')]()
  File "/usr/lib/python3/dist-packages/jdssc/pool.py", line 92, in volumes
    volumes.Volumes(self.args, self.uargs, self.jdss)
  File "/usr/lib/python3/dist-packages/jdssc/volumes.py", line 46, in __init__
    self.vsa[action]()
  File "/usr/lib/python3/dist-packages/jdssc/volumes.py", line 113, in create
    self.jdss.create_volume(name, size,
  File "/usr/lib/python3/dist-packages/jdssc/jovian_common/driver.py", line 103, in create_volume
    self.ra.create_lun(vname,
  File "/usr/lib/python3/dist-packages/jdssc/jovian_common/rest.py", line 168, in create_lun
    if not resp["error"] and resp["code"] in (200, 201):
           ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by mpimper** [comment]
thank for your reply , it is a testing environment, 
can I use previous version on production ?
proxmoz 8.2

**Comment by andreiperepiolkin** [comment]
I would recommend you to wait for newer version to appear as it introduces several fixes. We are testing it now.
Also can you please name the version of JovianDSS you are using?

**Comment by mpimperakias** [comment]
> @mpimper I would recommend you to wait for newer version to appear as it introduces several fixes. We are testing it now. I will post pre-release today with `shared` option added.

thanks for clarification 
i am waiting for your news, in the meantime can i use in the production [v0.9.7] or wait?

**Comment by andreiperepiolkin** [comment]
@mpimperakias, thank you for your patience. Im in a process of testing pre-release code. Will post it ASAP.

Also I've investigated a bit more the config file that you have provided.
I think another point of failure might be turning off ssl with "driver_use_ssl: False" for `/etc/pve/jdss-Pool-0.yaml`
Please check https://github.com/open-e/JovianDSS-Proxmox/blob/main/Makefile version of config, it represent current configuration options.
In particular, I would recommend setting flags in `/etc/pve/jdss-Pool-0.yaml`:
```yaml
driver_use_ssl: True
driver_ssl_cert_verify: False
 ```

**Comment by mpimper** [comment]
Good morning Andrei, before I change SSL is off, I try with enable SSL but
return SSL error, because is a test environment, needs commercial ssl ?

**Comment by andreiperepiolkin** [comment]
May be you have stumbled upon ssl certificate verification error. To avoid it there is flag `driver_ssl_cert_verify: False` it is added in 9.8 pre-release versions.
So as I said before, please enable both flags ON(True):

```yaml
driver_use_ssl: True
driver_ssl_cert_verify: False
```

JovianDSS trial version does not restrict certificate and ssl usage.

**Comment by andreiperepiolkin** [comment]
@mpimper  Ive uploaded v0.9.8-5 as pre release.
https://github.com/open-e/JovianDSS-Proxmox/releases/download/v0.9.8-5/open-e-joviandss-proxmox-plugin-v0.9.8-5.deb

Our team is testing it. You can try it for NON production usage.
It will be production ready once our team approves it.
Also I would recommend you start with this version(0.9.8-5) in opposite to 0.9.7 as it resolves significant amount of problems.

**Comment by mpimper** [comment]
thanks a lot , 👍🙏

**Comment by mpimper** [comment]
I will testing tomorrow and I will be back for notes 🎶

**Comment by andreiperepiolkin** [comment]
I think issue was resolved.

**Comment by mpimperakias** [comment]
Κωνσταντίνος Παππάς 
Tel: +30 2114007053 
Web: www.think-open.gr 
Email: ***@***.***
